name: Rich Code Nav Indexer
description: Indexes a repo to the Rich Code Nav cloud service
author: Microsoft
branding:
  icon: git-merge
  color: yellow

inputs:
  repo-token:
    description: Your GITHUB_TOKEN. Only necessary for private repositories.
    required: false
  languages:
    description: List of languages to use when discovering repository symbols, separated by ','
    required: false
  nugetFeed:
    description: Feed source to use when installing Rich Code Navigation NuGet packages
    required: false
  nugetVersion:
    description: Version of Rich Code Navigation packages to install, defaults to latest published
    required: false
  environment:
    description: 'The Rich Code Navigation environment to upload the index to. One of: production, staging or development.'
    required: false
  richNavLogOutputDirectory:
    description: A comma-separated list of log files created from the build when RichCodeNav.EnvVarDump is a package reference
    required: false
  soureRootDir:
    description: The directory on the machine where the source code is located, if different from the default.
    required: false
  configFiles: 
    description: The config file(s) for the project(s) to be indexed either as glob patterns or specific file paths relative to the root of the repo, separated by ','
    required: false
  maxParallelIndexingJobs:
    description: Enter a number between 1-4 to change the maximum number of parallel indexing jobs. Defaults to 2.
    required: false
  typescriptVersion:
    description: Optional version of TypeScript tools to use. See https://www.npmjs.com/package/lsif
    required: false

outputs:
  lspLogsPath:
    description: The path to LSP logs that may be uploaded as an artifact for diagnostics.

runs:
  using: node12
  main: lib/yarn-bootstrap.js
